version: '3.8'
services:
  nginx-rtmp:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "1935:1935"  # RTMP ingest
      - "8080:80"    # HTTP for HLS playback
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/tmp/hls
    restart: unless-stopped
